let Places = ['Paris', 'Tokyo', 'Egypt', 'New York', 'Sydney'];
console.log('Original Order:', Places);
console.log('Alphabetical Order:', [...Places].sort());
console.log('Reverse Alphabetical Order:', [...Places].sort().reverse());
console.log('Original Order:', Places);
Places.reverse();
console.log('Reversed Order:', Places);
Places.reverse();
console.log('Original Order:', Places);
Places.sort();
console.log('Alphabetical Order:', Places);
Places.sort().reverse();
console.log('Reverse Alphabetical Order:', Places);
